[package]
name = "integration-tests"
version = "1.0.0"
authors = []
edition = "2018"

[dependencies]
near-sdk = "4.1.1"
near-contract-standards = "4.1.1"
near-units = "0.2.0"
workspaces = "0.7.0"
anyhow = "1.0.68"
tokio = "1.24.1"

[[example]]
name = "integration-tests"
path = "src/lib.rs"
